### ISSUE TITLE
Error for Craftbukkit R6 (MC: 1.2.2 )

### ISSUE THREAD

**Issue by XxCoolGamesxX** [BR-/WaterproofRedstone#1]
What steps will reproduce the problem?
1. Start the server.

What version of the product are you using?
WaterproofRedstone v0.2

Do you have an error log of what happened?

Error occurred while enabling WaterproofRedstone v0.2 (Is it up to date?)
java.lang.NoSuchMethodError: me.br_.minecraft.bukkit.waterproofredstone.WRMain.getConfiguration()Lorg/bukkit/util/config/Configuration;
    at me.br_.minecraft.bukkit.waterproofredstone.WRMain.onEnable(WRMain.java:17)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:363)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:250)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:232)
    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:369)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:356)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:187)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:420)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:490)

Please provide any additional information below.

I tested WaterproofRedstone v0.2 with Craftbukkit R6 (MC: 1.2.2 ) and it will break.

I know that your plugin is from 1.7.3 but it did work for 1.1.

**Comment by BR-** [comment]
As I understand it, Bukkit's configuration system changed recently. WaterproofRedstone depends on the older configuration, so newer builds of Bukkit will break it. School has started back up again, and I haven't been maintaining my plugins - I probably won't update it in a timely manner. Sorry :(
